### ISSUE TITLE
Create readme.md

### ISSUE THREAD

**Issue by izabela1337** [Hazeliusz/babynames-scraper#1]
![image](https://user-images.githubusercontent.com/54004218/118171418-7f768800-b42b-11eb-896f-feba8c635121.png)

**Comment by izabela1337** [comment]
we've been bamboozled

**Comment by HazelWentNuts** [comment]
<img width="244" alt="Untitled" src="https://user-images.githubusercontent.com/49100171/118409462-db8b1780-b68a-11eb-9fad-7e3e5b52b580.png">
